services:
  app:
    container_name: "${COMPOSE_PROJECT_NAME}-graphql"
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

networks:
  default:
    name: "${COMPOSE_PROJECT_NAME}_default"