services:
  master:
    container_name: "master_db"
    build:
      context: .
      dockerfile: Dockerfile.citus.arm64
    ports: ["${COORDINATOR_EXTERNAL_PORT:-5432}:5432"]
    labels: ["com.citusdata.role=Master"]
    environment: &AUTH
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGUSER: "${POSTGRES_USER:-postgres}"
      PGPASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-trust}"
  worker:
    image: "citusdata/citus:11.3.0"
    labels: ["com.citusdata.role=Worker"]
    depends_on: [manager]
    environment: *AUTH
    command: "/wait-for-manager.sh"
    deploy:
      replicas: 2
    volumes:
      - healthcheck-volume:/healthcheck
  manager:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}-db_manager"
    image: "citusdata/membership-manager:0.3.0"
    volumes:
      - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
      - healthcheck-volume:/healthcheck
    depends_on: [master]
    environment: *AUTH
  cache:
    container_name: "${COMPOSE_PROJECT_NAME}-cache"
    image: "redis:alpine"
    ports: ["6379:6379"]
  vernemq:
    container_name: "${COMPOSE_PROJECT_NAME}-vernemq"
    image: "vernemq/vernemq:latest"
    ports:
      - "1883:1883"
      - "8081:8080"
      - "8888:8888"

    environment:
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=off
      - DOCKER_VERNEMQ_PERSISTENT_CLIENT_EXPIRATION=1w
      - DOCKER_VERNEMQ_PLUGINS__VMQ_ACL=off
      - DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD=off
      - DOCKER_VERNEMQ_PLUGINS__VMQ_WEBHOOKS=on
      - DOCKER_VERNEMQ_VMQ_WEBHOOKS__AUTH_ON_REG__ENDPOINT=http://bubble-api-graphql:8080/api/webhook/vmq/auth_on_register
      - DOCKER_VERNEMQ_VMQ_WEBHOOKS__AUTH_ON_REG__HOOK=auth_on_register
      - DOCKER_VERNEMQ_VMQ_WEBHOOKS__AUTH_ON_PUB__ENDPOINT=http://bubble-api-graphql:8080/api/webhook/vmq/auth_on_publish
      - DOCKER_VERNEMQ_VMQ_WEBHOOKS__AUTH_ON_PUB__HOOK=auth_on_publish
      - DOCKER_VERNEMQ_VMQ_WEBHOOKS__AUTH_ON_SUB__ENDPOINT=http://bubble-api-graphql:8080/api/webhook/vmq/auth_on_subscribe
      - DOCKER_VERNEMQ_VMQ_WEBHOOKS__AUTH_ON_SUB__HOOK=auth_on_subscribe
volumes:
  healthcheck-volume:

networks:
  default:
    name: "${COMPOSE_PROJECT_NAME}_default"